Repository openshift/knative-build, pull requests merged in 2018-11, with the labels that each got.

#2 OpenShift CI - e2e tests
  Makefile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/creds-init/Dockerfile
  openshift/ci-operator/knative-images/git-init/Dockerfile
  openshift/ci-operator/knative-images/nop/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
  openshift/ci-operator/knative-test-images/panic/Dockerfile
  openshift/e2e-tests-openshift.sh
  vendor/github.com/knative/pkg/test/e2e_flags.go
Labels: lgtm, size/L

#6 add OWNERS_ALIASES for knative-build
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, size/M

#5 add OWNERS_ALIASES for knative-build
  OWNERS
  OWNERS_ALIASES
Labels: size/M

#9 Enable admission webhooks in CI
  openshift/admission-webhooks.yaml
  openshift/e2e-tests-openshift.sh
  test/e2e/simple_test.go
Labels: approved, lgtm, size/M

#8 Enable admission webhooks in CI
  openshift/admission-webhooks.yaml
  openshift/e2e-tests-openshift.sh
  test/e2e/simple_test.go
Labels: approved, lgtm, size/M
