Repository openshift/knative-build, pull requests merged in 2019-04, with the labels that each got.

#33 Adding release preparation scripts…
  openshift/release/README.md
  openshift/release/create-release-branch.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/M

#34 CI was here
  ci
Labels: approved, lgtm, size/XS

#36 Replaces fix
  openshift/olm/knative-build.catalogsource.yaml
  openshift/olm/knative-build.v0.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#38 fixing minor typos
  README.md
Labels: approved, lgtm, size/XS

#37 CI was here
  ci
  test/e2e/simple_test.go
  test/sources/test3.yaml
Labels: approved, lgtm, size/XS

#39 Fix for race condition that results in update [SRVCOM-438]
  openshift/olm/knative-build.catalogsource.yaml
  openshift/olm/knative-build.v0.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test, size/S

#40 SRVCOM 438
  openshift/olm/knative-build.catalogsource.yaml
  openshift/olm/knative-build.v0.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test, size/S

#41 Release yaml scripts
  Makefile
  openshift/admission-webhooks.yaml
  openshift/e2e-tests-openshift.sh
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/knative-build-v0.5.0.yaml
  openshift/release/resolve.sh
Labels: approved, lgtm, size/XL

#42 Release yaml scripts master
  Makefile
  openshift/admission-webhooks.yaml
  openshift/e2e-tests-openshift.sh
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
Labels: approved, lgtm, size/L

#43 Updating openshift specific files.
  openshift/e2e-tests-openshift.sh
  openshift/olm/knative-build.catalogsource.yaml
  openshift/olm/knative-build.crd.yaml
  openshift/olm/knative-build.package.yaml
  openshift/olm/knative-build.v0.4.0.clusterserviceversion.yaml
  openshift/release/README.md
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/XL

#44 Latest 0.5.0 CatalogSource
  openshift/olm/README.md
  openshift/olm/knative-build.catalogsource.yaml
  openshift/olm/knative-build.crd.yaml
  openshift/olm/knative-build.package.yaml
  openshift/olm/knative-build.v0.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XL
